FROM 471860524421.dkr.ecr.eu-west-1.amazonaws.com/bwce-base:latest
# FROM ubuntu:latest
LABEL maintainer="Hugo Peters <hugo.peters@cloud.com>"
# Install any necessary packages
ADD ./EARs/PGDatabaseManager.ear /
EXPOSE 8080
EXPOSE 8090
EXPOSE 7777

